version: '3.8'

services:
  redis:
    image: redis:7.2.0-alpine
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - 6379
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_PASSWORD:0913
      - REDIS_PORT:6379

volumes:
  redis_data:
